export { validateCPF } from './validateCPF'
export { validateCNPJ } from './validateCNPJ'
export { validateEmail } from './validateEmail'
export { validateTelephone } from './validateTelephone'
export { validatePasswordStrong } from './validatePasswordStrong'
